name: Trigger auto deployment for py01

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/py01-AutoDeployTrigger-2add9ec7-e769-4a1b-95f6-48655ed36d60.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PY01_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PY01_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PY01_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.PY01_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PY01_REGISTRY_PASSWORD }}
          containerAppName: py01
          resourceGroup: Python-Container-App
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


